### ISSUE TITLE
content not changing/moving

### ISSUE THREAD

**Issue by edumusa** [jlethuau/wp-parallax-content-slider#58]
hello,
i'm having some trouble with parallax content slider, but didn't find any issues like mine in the support. As i navigate, some text move, but others remain fixed. Already tested with all other plugin disabled and original wp theme. 
Please take a look at http://oycos.com.br/producao/parallaxer/
thanx, regards,
eduardo

**Comment by alex80ks** [comment]
I think that is maybe, i just say maybe Jquery problem.... i found out this on your website 
"jQuery.attrFn is deprecated", "jQuery.browser is deprecated"
try to install plugin Jquery updater to check that maybe solve your problem becouse he will deregister old and set new one. Give it a try.

**Comment by edumusa** [comment]
hello alex, thank you for the help, but that didn't work... installed, activated, but still no good... by the way, how did you find the error?

**Comment by alex80ks** [comment]
Firebug helped me....try set default theme and turn off plugin that you use for background and clear the cache. By the way are you using some cache plugin?

**Comment by edumusa** [comment]
ok… well i already have tried that, didn't work, now i tried again, no plugins, twentyeleven on, empty browser cache, test on FF, chrome, safari, but nothing… actually there are some over ridding text as well… no cache plugin here... oh gosh!

**Comment by alex80ks** [comment]
I noticed that your footer overlap your slider when you slide down (if you cant slide your page down to see use zoom tool in your browser) and that can be z-index. Also your theme is not on wordpress repository so that can be multiple reasons that causing the problem.

**Comment by alex80ks** [comment]
your slider backgorund are visible now... your plugin for sliding backgorund was saying this
a.fwb_fromthis img{position:fixed;bottom:10px;right:10px;z-index:999999999;   notice z-index?
now with default theme background is visible and only text left to fix. Try enter some text insted of shortcodes

**Comment by alex80ks** [comment]
Turn off paralaxer-2 it seems that scripts sre loaded on each page (parallaxer and parallaxer 2) just leave problematic plugin on

**Comment by alex80ks** [comment]
this is my html code h2Најлепша места на свету &#8211; Тун.../h2     p Тунел Љубави &#8211; Украјина Представљамо вам једно од најлепших пејзажа на свету &#8211; Тунел Љубави. Овај дуги, предивни лиснати тунел изгледа као зелени сан или сцена из филма &#8211; заправо ово место заиста постоји и може се наћи дубоко у шумама Украјине. Како изгледа погледајте сами.Тунел се налази у близини града Клевен, овај раскошни зелени [&hellip;] /p     and this is yours
h2estilo/h2
p p A decoração do espaço foi inspirada na barbearia do avô de André Mateus, combinando o estilo retrô com elementos urbanos.
/p
pEsse mix de influências imprime a personalidade do salão e transforma o local em um ambiente descontraído e inspirador.
/p
p Agende uma visita à Cabelaria e experimente descobrir alguém novo sem deixar de ser você.
/p
pCabelaria, cada cabeça uma transformação.
/p /p   ............... I have one p tag with text and you have several,also pay attension to last p tag in your code.That is maybe added by auto-p by wordpress and made overlapping text. p cannot contain another p, due to being a phrasing content.

**Comment by alex80ks** [comment]
So conclusion is if you have more than 1 p tag with 50 characters you will get all p tags shown one above the other just like in your case. 
this as it should be code...use Firebug and live edit and remove all other p tag just leave one....then try it...
h2estilo/h2
pA decoração do espaço foi inspirada na barbearia do avô de André Mateus, combinando o estilo retrô com elementos urbanos. /p

**Comment by edumusa** [comment]
ok alex, thanks again! And after your advises it is working fine now... I just wanted to show more content and with more p and other tags....i'll think of something else... Thank you very much for all your attention! Best Regards.

**Comment by alex80ks** [comment]
Youre welcome... Avoid to use another plugin shortcode in existing plugin becouse this what you have done unless you are 100% sure......Here is some tip for you.... i saw that you didnt use background for slider. You can use gradient background with some opacity... ;)
Best Regards.
